services:
  - type: web
    name: student-pro
    runtime: python
    # Указываем правильный путь к требованиям
    buildCommand: "pip install -r backend/requirements.txt"
    # Запускаем через модуль, чтобы Python корректно видел проект
    startCommand: "python -m gunicorn --chdir backend config.wsgi:application"